project:
  type: default
  output-dir: _manuscript
  # render: 
  #   - "sections/"
  # - "notebooks/thesis.qmd"
    # - "presentations/full_slides.qmd"

# manuscript:
#   article: index.qmd

execute:
  freeze: false
  echo: false
  warning: false
  message: false

bibliography: references.bib
license: "CC BY-NC"

references: references.bib
citeproc: true
csl: https://www.zotero.org/styles/begell-house-chicago-author-date
# Add the wp profile

