project:
  render:
    - thesis.qmd


format: 
  pdf: 
    geometry: paperheight=22.5cm,paperwidth=17cm
    documentclass: report
    linestretch: 1.25
    fontfamily: libertinus
    fontsize: 4pt
    dpi: 300
    colorlinks: false
    include-in-header: 
      text: |
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
        \usepackage{amsmath}
    includes:
      in_header: 'gt_packages.sty'
    number-sections: true
    number-depth: 3
    shift-heading-level-by: -1
    toc: true
    toc-depth: 2
    lot: true
    lof: true
    link-citations: true
    notebook-links: false
    fig-cap-location: top

# You can add thesis-only front matter defaults here:
# metadata-files: []

# Optional: set a profile flag you can test in content
# (used if you choose conditional gating in a single main file)
# profile: thesis
