project:
  type: manuscript

  render: 
 #   - "notebooks/"
    - "index.qmd"
    # - "presentations/04_final.qmd"


manuscript:
  article: index.qmd


title: "The Labor Market Outcomes of (Quasi) Unemployment Insurance"
subtitle: "Evidence from the *Retiro Parcial por Desempleo* in Mexico"
authors:
  - name: Esteban Degetau
    affiliation: Instituto Mexicano del Seguro Social
    roles: writing
    corresponding: true

format:
  # html:
  #   comments:
  #     hypothesis: true
  # jats: default

  # Thesis format
  pdf: 
      geometry: paperheight=22.5cm,paperwidth=17cm
      documentclass: report
      linestretch: 1.25
      fontfamily: libertinus
      fontsize: 4pt
      dpi: 300
      colorlinks: false
      include-in-header: 
        text: |
          \usepackage{lscape}
          \newcommand{\blandscape}{\begin{landscape}}
          \newcommand{\elandscape}{\end{landscape}}
          \usepackage{amsmath}
      #    \usepackage[font=footnotesize,labelfont={bf,footnotesize}]{caption}
      includes:
        in_header: 'gt_packages.sty'
      number-sections: true
      number-depth: 3
      shift-heading-level-by: -1
      toc: true
      toc-depth: 2
      lot: true
      lof: true
      link-citations: true
      notebook-links: false
      fig-cap-location: top

execute:
  freeze: auto

bibliography: references.bib
