project:
  type: default
  output-dir: _manuscript
  render:
      - wp.qmd
      - slides/rpd-talk.qmd



profile:
  default: wp

execute:
  freeze: false
  echo: false
  warning: false
  message: false

bibliography: references.bib
citeproc: true

license: "CC BY-NC"
keywords: [unemployment insurance, income substitution, Mexico, RPD, labor economics]
