project:
  type: default
  output-dir: _manuscript
  # render: 
  #   - "sections/"
  # - "notebooks/thesis.qmd"
    # - "presentations/full_slides.qmd"

# manuscript:
#   article: index.qmd

profile:
  default: wp

execute:
  freeze: false
  echo: false
  warning: false
  message: false


# Add the wp profile

