---
title: "Difference-in-differences"
format: html
---


```{r}

rm(list = ls())
gc()

pacman::p_load(
    here,
    tidyverse,
    arrow,
    did,
    gt,
    gtsummary,
    janitor
)

set.seed(20250116)

```

```{r}

did_data <- here("data/anon/did") |>
    open_dataset(format = "parquet")

at_unemployment <- did_data |>
    filter(unemp_t == 0) |>
    collect()


if(interactive()) {
    
    at_unemployment <- at_unemployment |>
        sample_n(1000)

    did_data <- did_data |>
        inner_join(
            at_unemployment |> select(worker_id),
            by = "worker_id",
            copy = T
        ) |>
    compute()
}


did_2020 <- did_data |>
    filter(year(period) == 2020) |>
    compute()



```


## Different eligibility windows

```{r}
my_cs_wy <- function(LHS, eligibility_limit) {
  
  ready_data_f <- did_2020 |>
    mutate(
      within_year = as.numeric(weeks_to_elig_u <= eligibility_limit),
      cohort = case_when(
        within_year == 0 ~ 0,
        T ~ unemp_g - 5
      ),
      treat = as.numeric(t >= cohort & cohort > 0 & within_year == 1),
      unemp_t = unemp_t - 5
    ) |>
    collect()
  
  cs_1 <- att_gt(
    yname = LHS,
    tname = "unemp_t",
    idname = "worker_id",
    gname = "within_year",
    allow_unbalanced_panel  = T,
    data = ready_data_f,
    control_group = "nevertreated",
    anticipation = 0,
    base_period = "universal"
  )
  
  return(cs_1)
}

```

```{r}

outcome_vars <- c("employment", "density", "income", "wage")

estimation <- tibble(
  LHS = outcome_vars,
  eligibility_limit = list(c(52, 26, 13))
) |>
  unnest(eligibility_limit) |>
  mutate(
    cs = map2(LHS, eligibility_limit, my_cs_wy, .progress = T)
  )

```


```{r}

event_study_plots <- estimation |>
  filter(eligibility_limit == 52) |>
  mutate(
    event_study = map(
      cs,
      ~ .x |> aggte("dynamic", na.rm = T)
    )
  ) |>
  pull(event_study)


point_estimates <- estimation |>
  mutate(
    point_estimate = map(cs, ~ .x |> aggte("simple", na.rm = T)),
    Estimate = map_dbl(point_estimate, ~ pluck(.x, "overall.att")),
    SE = map_dbl(point_estimate, ~ pluck(.x, "overall.se"))
  ) 

```

```{r}
#| label: tbl-itt
#| tbl-cap: Effect of UI eligibility on labor market outcomes


means <- did_data |>
  select(
    wage,
    density,
    employment,
    # rpd_it,
    # rpd_no_cum,
    income) |>
  summarise(across(
    everything(),
    ~ mean(.x, na.rm = T)
  )) |>
  collect() |>
  rename(
    # "Cumulative take-up" = rpd_it,
    # "Weekly take-up" = rpd_no_cum,
    "Employment" = employment,
    "Contribution density" = density,
    "Weekly income (2024 MXN)" = income,
    "Daily wage (2024 MXN)" = wage
  ) |>
  mutate(
    window = "Statistics",
    type = "Mean"
  ) 

sds <- did_data |>
  select(
    wage,
    density,
    employment,
    # rpd_it,
    # rpd_no_cum,
    income) |>
  summarise(across(
    everything(),
    ~ sd(.x, na.rm = T)
  )) |>
  collect() |>
  rename(
    # "Cumulative take-up" = rpd_it,
    # "Weekly take-up" = rpd_no_cum,
    "Employment" = employment,
    "Contribution density" = density,
    "Weekly income (2024 MXN)" = income,
    "Daily wage (2024 MXN)" = wage
  ) |>
  mutate(
    window = "Statistics",
    type = "SD"
  )



nobs <- point_estimates |>
  mutate(
    N = map_dbl(point_estimate, ~ pluck(.x, "DIDparams", "n")),
  ) |>
  distinct(LHS, N) |>
  mutate(
    LHS = case_when(
      LHS == "rpd_it" ~ "Cumulative take-up",
      LHS == "rpd_no_cum" ~ "Weekly take-up",
      LHS == "employment" ~ "Employment",
      LHS == "density" ~ "Contribution density",
      LHS == "income" ~ "Weekly income (2024 MXN)",
      LHS == "wage" ~ "Daily wage (2024 MXN)"
    )
  ) |>
  pivot_wider(
    names_from = LHS,
    values_from = N
  ) |>
  mutate(window = "Statistics", type = "N")

point_estimates |>
  select(LHS, window = eligibility_limit, Estimate, SE) |>
  mutate(
    label = case_when(
      LHS == "rpd_it" ~ "Cumulative take-up",
      LHS == "rpd_no_cum" ~ "Weekly take-up",
      LHS == "employment" ~ "Employment",
      LHS == "density" ~ "Contribution density",
      LHS == "income" ~ "Weekly income (2024 MXN)",
      LHS == "wage" ~ "Daily wage (2024 MXN)"
    ),
    window = str_c("Weeks to eligibility: ", window)
  ) |>
  pivot_longer(c(Estimate, SE),
               names_to = "type",
               values_to = "value") |>
  pivot_wider(
    names_from = label,
    values_from = value,
    id_cols = c(window, type)
  ) |>
  add_row(means) |>
  add_row(sds) |>
  add_row(nobs) |>
  group_by(window) |>
  gt(
    rowname_col = "type"
  ) |>
  tab_footnote(
    md("*Note:* This table shows the effect of becoming eligible to UI benefits on labor market outcomes as estimated in Equation 4.1, estimated using Callaway and Sant'Anna (2021) under three different settings. Each panel assigns the treatment status to workers who will become eligible within different windows: 52, 26 and 13 weeks since the start of the unemployment spell, and are considered control otherwise. The estimates are are expressed in percentage points for columns 1 to 4, and in 2024 Mexican pesos for the and wage mass. Standard errors are clustered at the worker level."),
  ) |>
  fmt_number(
    decimals = 3,
    drop_trailing_zeros = T
  ) |>
  cols_width(
    where(is.numeric) ~ pct(15),
    everything() ~ pct(10)
  ) |>
  tab_options(
    table.font.size = pct(60),
    table.width = pct(100),
    quarto.use_bootstrap = TRUE
  ) 

```


```{r}
#| label: fig-event-study
#| fig-cap: "Weekly event-study estimates and 95 percent confidence intervals of the effect of UI eligibility on labor market outcomes within 2020"
#| fig-alt: "Weekly estimates of the effect of UI eligibility on labor market outcomes. The estimates are expressed in percentage points subfigures 1 through 4, and in 2024 Mexican pesos for the wage mass. The shaded area represents the 95% confidence interval."
#| layout-ncol: 2
#| fig-subcap: 
#|  - Cumulative take-up
#|  - Weekly take-up
#|  - Employment
#|  - Contribution density
#|  - Weekly income (2024 MXN)
#|  - Daily wage (2024 MXN)
#| fig-height: 3
#| fig-width: 4

my_event_study_plot <- function(x) {
  
  
  cs.output <- cbind.data.frame(
    Estimate = x$att.egt,
    SE = x$se.egt,
    time = x$egt
  )
  
  event_study <- cs.output %>%
    as_tibble() |>
    dplyr::mutate(
      lower = Estimate - (1.96 * SE),
      upper = Estimate + (1.96 * SE),
      type = "CS"
    )  %>%
    janitor::clean_names() %>%
    dplyr::select(-se)
  
  event_study |>
    ggplot(aes(time, estimate)) +
    # geom_pointrange(aes(ymin = lower, ymax = upper)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), fill = "lightblue", alpha = 0.5) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_vline(xintercept = 0, linetype = "dotted") +
    geom_line() +
    labs(
      x = "Weeks to eligibility",
      y = "Estimate"
    ) +
    xlim(-25, 40)
  
  
}






walk(
  event_study_plots,
  ~ .x |> my_event_study_plot() |> print()
  
)



```


## Different pre-employment periods


```{r}
my_cs_wy <- function(LHS, employment_limit) {
  ready_data_f <- did_2020 |>
    filter(periods_employed_before >= employment_limit) |>
    mutate(
      within_year = as.numeric(weeks_to_elig_u <= 52),
      cohort = case_when(
        within_year == 0 ~ 0,
        T ~ unemp_g - 5
      ),
      treat = as.numeric(t >= cohort & cohort > 0 & within_year == 1),
      unemp_t = unemp_t - 5
    ) |>
    collect()
  
  cs_1 <- att_gt(
    yname = LHS,
    tname = "unemp_t",
    idname = "worker_id",
    gname = "within_year",
    allow_unbalanced_panel  = T,
    data = ready_data_f,
    control_group = "notyettreated",
    anticipation = 0,
    base_period = "universal"
  )
  
  return(cs_1)
}

```

```{r}

outcome_vars <- c("employment", "density", "income", "wage")

estimation_emp <- tibble(
  LHS = outcome_vars,
  employment_limit = list(c(52, 26, 13))
) |>
  unnest(employment_limit) |>
  mutate(
    cs = map2(LHS, employment_limit, my_cs_wy, .progress = T)
  )

```


```{r}

did_data |>
  summarise(.by = worker_id,
            n_t = n_distinct(t),
            n_pep = n_distinct(periods_employed_before)
            ) |>
  select(!worker_id) |>
  collect() |>
  tbl_summary()

plot_data <- did_data |>
  filter(periods_employed_before >= 52) |>
    mutate(
      within_year = as.numeric(weeks_to_elig_u <= 52),
      cohort = case_when(
        within_year == 0 ~ 0,
        T ~ unemp_g - 5
      ),
      treat = as.numeric(t >= cohort & cohort > 0 & within_year == 1),
      unemp_t = unemp_t - 5
    ) 
  
plot_data |>
  collect() |>
  ggplot(aes(t, employment, color = factor(treat))) +
  stat_summary(geom = "line", fun = ~ mean(.x, na.rm = T))

```



```{r}

event_study_plots <- estimation_emp |>
  filter(employment_limit == 26) |>
  mutate(
    event_study = map(
      cs,
      ~ .x |> aggte("dynamic", na.rm = T)
    )
  ) |>
  pull(event_study)


point_estimates <- estimation_emp |>
  mutate(
    point_estimate = map(cs, ~ .x |> aggte("simple", na.rm = T)),
    Estimate = map_dbl(point_estimate, ~ pluck(.x, "overall.att")),
    SE = map_dbl(point_estimate, ~ pluck(.x, "overall.se"))
  ) 

```

```{r}
#| label: tbl-itt
#| tbl-cap: Effect of UI eligibility on labor market outcomes


means <- did_data |>
  select(
    wage,
    density,
    employment,
    # rpd_it,
    # rpd_no_cum,
    income) |>
  summarise(across(
    everything(),
    ~ mean(.x, na.rm = T)
  )) |>
  collect() |>
  rename(
    # "Cumulative take-up" = rpd_it,
    # "Weekly take-up" = rpd_no_cum,
    "Employment" = employment,
    "Contribution density" = density,
    "Weekly income (2024 MXN)" = income,
    "Daily wage (2024 MXN)" = wage
  ) |>
  mutate(
    window = "Statistics",
    type = "Mean"
  ) 

sds <- did_data |>
  select(
    wage,
    density,
    employment,
    # rpd_it,
    # rpd_no_cum,
    income) |>
  summarise(across(
    everything(),
    ~ sd(.x, na.rm = T)
  )) |>
  collect() |>
  rename(
    # "Cumulative take-up" = rpd_it,
    # "Weekly take-up" = rpd_no_cum,
    "Employment" = employment,
    "Contribution density" = density,
    "Weekly income (2024 MXN)" = income,
    "Daily wage (2024 MXN)" = wage
  ) |>
  mutate(
    window = "Statistics",
    type = "SD"
  )



nobs <- point_estimates |>
  mutate(
    N = map_dbl(point_estimate, ~ pluck(.x, "DIDparams", "n")),
  ) |>
  distinct(LHS, N) |>
  mutate(
    LHS = case_when(
      LHS == "rpd_it" ~ "Cumulative take-up",
      LHS == "rpd_no_cum" ~ "Weekly take-up",
      LHS == "employment" ~ "Employment",
      LHS == "density" ~ "Contribution density",
      LHS == "income" ~ "Weekly income (2024 MXN)",
      LHS == "wage" ~ "Daily wage (2024 MXN)"
    )
  ) |>
  pivot_wider(
    names_from = LHS,
    values_from = N
  ) |>
  mutate(window = "Statistics", type = "N")

point_estimates |>
  select(LHS, window = employment_limit, Estimate, SE) |>
  mutate(
    label = case_when(
      LHS == "rpd_it" ~ "Cumulative take-up",
      LHS == "rpd_no_cum" ~ "Weekly take-up",
      LHS == "employment" ~ "Employment",
      LHS == "density" ~ "Contribution density",
      LHS == "income" ~ "Weekly income (2024 MXN)",
      LHS == "wage" ~ "Daily wage (2024 MXN)"
    ),
    window = str_c("Weeks to eligibility: ", window)
  ) |>
  pivot_longer(c(Estimate, SE),
               names_to = "type",
               values_to = "value") |>
  pivot_wider(
    names_from = label,
    values_from = value,
    id_cols = c(window, type)
  ) |>
  add_row(means) |>
  add_row(sds) |>
  add_row(nobs) |>
  group_by(window) |>
  gt(
    rowname_col = "type"
  ) |>
  tab_footnote(
    md("*Note:* This table shows the effect of becoming eligible to UI benefits on labor market outcomes as estimated in Equation 4.1, estimated using Callaway and Sant'Anna (2021) under three different settings. Each panel assigns the treatment status to workers who will become eligible within different windows: 52, 26 and 13 weeks since the start of the unemployment spell, and are considered control otherwise. The estimates are are expressed in percentage points for columns 1 to 4, and in 2024 Mexican pesos for the and wage mass. Standard errors are clustered at the worker level."),
  ) |>
  fmt_number(
    decimals = 3,
    drop_trailing_zeros = T
  ) |>
  cols_width(
    where(is.numeric) ~ pct(15),
    everything() ~ pct(10)
  ) |>
  tab_options(
    table.font.size = pct(60),
    table.width = pct(100),
    quarto.use_bootstrap = TRUE
  ) 

```


```{r}
#| label: fig-event-study
#| fig-cap: "Weekly event-study estimates and 95 percent confidence intervals of the effect of UI eligibility on labor market outcomes within 2020"
#| fig-alt: "Weekly estimates of the effect of UI eligibility on labor market outcomes. The estimates are expressed in percentage points subfigures 1 through 4, and in 2024 Mexican pesos for the wage mass. The shaded area represents the 95% confidence interval."
#| layout-ncol: 2
#| fig-subcap: 
#|  - Cumulative take-up
#|  - Weekly take-up
#|  - Employment
#|  - Contribution density
#|  - Weekly income (2024 MXN)
#|  - Daily wage (2024 MXN)
#| fig-height: 3
#| fig-width: 4

my_event_study_plot <- function(x) {
  
  
  cs.output <- cbind.data.frame(
    Estimate = x$att.egt,
    SE = x$se.egt,
    time = x$egt
  )
  
  event_study <- cs.output %>%
    as_tibble() |>
    dplyr::mutate(
      lower = Estimate - (1.96 * SE),
      upper = Estimate + (1.96 * SE),
      type = "CS"
    )  %>%
    janitor::clean_names() %>%
    dplyr::select(-se)
  
  event_study |>
    ggplot(aes(time, estimate)) +
    # geom_pointrange(aes(ymin = lower, ymax = upper)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), fill = "lightblue", alpha = 0.5) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_vline(xintercept = 0, linetype = "dotted") +
    geom_line() +
    labs(
      x = "Weeks to eligibility",
      y = "Estimate"
    ) +
    xlim(-25, 40)
  
  
}






walk(
  event_study_plots,
  ~ .x |> my_event_study_plot() |> print()
  
)



```

